/**
 * ═══════════════════════════════════════════════════════════════════════════
 * GENESIS TUTORIAL APPLICATION
 * Refactored to match "Step-by-Step" design with Genesis aesthetics.
 * ═══════════════════════════════════════════════════════════════════════════
 */

const tutorialData = [
    {
        id: 'setup',
        title: 'Setup & Security',
        description: 'Full guide to creating your account, enabling 2FA, and securing your withdrawals.',
        icon: 'ph:shield-check-fill',
        steps: [
            {
                title: 'Sign Up',
                description: 'Start your Genesis journey. Register efficiently with a valid email. Ensure you choose a strong alphanumeric password for account safety.',
                image: 'images/tutorial/setup-01-sign-in-screen.jpg'
            },
            {
                title: 'Security Pin',
                description: 'Set a 6-digit Withdrawal Pin immediately after signing up. This code is required for all outgoing transactions.',
                image: 'images/tutorial/setup-05-set-withdrawal-password.jpg'
            },
            {
                title: 'Profile Settings',
                description: 'Navigate to your profile settings by clicking the icon in the top-left corner to begin security configuration.',
                image: 'images/tutorial/setup-03-press-user-icon-top-left.jpg'
            },
            {
                title: 'Enable 2FA',
                description: 'Select "Google Authenticator" to bind your device. 2FA prevents unauthorized withdrawals even if your password is compromised.',
                image: 'images/tutorial/setup-06-bind-google-authenticator-option.jpg'
            },
            {
                title: 'Copy Secret Key',
                description: 'Copy the unique secret key provided. You will need to paste this into your Google Authenticator app.',
                image: 'images/tutorial/setup-07-copy-your-secret-key.jpg'
            },
            {
                title: 'Verify Code',
                description: 'Enter the 6-digit code generated by your Authenticator app to finalize the binding process.',
                image: 'images/tutorial/setup-10-enter-code-details.jpg'
            },
            {
                title: 'Connect MT5',
                description: 'Link your MetaTrader 5 account by entering your login details in the connection settings.',
                image: 'images/tutorial/setup-14-fill-in-mt5-details.jpg'
            },
            {
                title: 'Deposit Funds',
                description: 'Select your preferred network (TRC20 or BEP20) to deposit funds. Always double-check the network address.',
                image: 'images/tutorial/wallet-03-select-network-trc20bep20.jpg'
            }
        ]
    },
    {
        id: 'signals',
        title: 'Trading & Signals',
        description: 'How to subscribe to AI signals or trade manually on the platform.',
        icon: 'ph:chart-line-up-bold',
        steps: [
            {
                title: 'Signal Subscription',
                description: 'Browse professional traders. Check their risk profiles and past performance before subscribing.',
                image: 'images/tutorial/signals-03-standard-signal-subscription.jpg'
            },
            {
                title: 'Confirm Subscription',
                description: 'Set your investment amount (Min $100) and choose between Standard or Insurance signal types.',
                image: 'images/tutorial/signals-06-standard-subscription-from-insurance-signal.jpg'
            },
            {
                title: 'View Pairs',
                description: 'Access the manual trading terminal to view available cryptocurrency pairs.',
                image: 'images/tutorial/signals-08-available-trading-pairs.jpg'
            },
            {
                title: 'Execute Trade',
                description: 'Enter your lot size and choose "Long" (Buy) or "Short" (Sell) based on your market analysis.',
                image: 'images/tutorial/signals-09-enter-lot-size-then-long-or-short.jpg'
            }
        ]
    },
    {
        id: 'provider',
        title: 'Signal Provider',
        description: 'Create your own signals and earn profit shares from copiers.',
        icon: 'ph:broadcast-bold',
        steps: [
            {
                title: 'Create Signal',
                description: 'Configure your signal parameters: Total Capital, Copy Period (e.g., 30 days), and Profit Split ratio.',
                image: 'images/tutorial/signals-12-standard-signal-form.jpg'
            }
        ]
    },
    {
        id: 'wallet',
        title: 'Wallet & Account',
        description: 'Manage your assets, understand balances, and community features.',
        icon: 'ph:wallet-fill',
        steps: [
            {
                title: 'Wallet Overview',
                description: 'Track your Total Assets, Available Balance (for trade/withdrawal), and Frozen Balance (locked in orders).',
                image: 'images/tutorial/wallet-11-genesis-wallet-overview.jpg'
            },
            {
                title: 'Withdraw Funds',
                description: 'Initiate a withdrawal request. Ensure your 2FA is active and you are using the correct network.',
                image: 'images/tutorial/wallet-06-funds-withdraw.jpg'
            },
            {
                title: 'Confirm Withdrawal',
                description: 'Review withdrawal details carefully before confirming. Security pin will be required.',
                image: 'images/tutorial/wallet-07-withdrawal-form.jpg'
            },
            {
                title: 'Group Chat',
                description: 'Join the global community chat to discuss trends and get support from other members.',
                image: 'images/tutorial/wallet-10-genesis-group-chat.jpg'
            },
            {
                title: 'Invite Friends',
                description: 'Copy your unique Broker Invitation Link to invite friends and grow your network.',
                image: 'images/tutorial/wallet-09-ib-broker-copy-invitation-link.jpg'
            }
        ]
    }
];

// State State
let state = {
    view: 'home', // 'home' | 'section'
    currentSectionIndex: null,
    currentStepIndex: 0,
    isAnimating: false
};

const appRoot = document.getElementById('app-root');

// ─────────────────────────────────────────────────────────────────────────────
// RENDER FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

function initApp() {
    renderHome();
}

function renderHome() {
    state.view = 'home';
    state.currentSectionIndex = null;
    state.currentStepIndex = 0;

    const gridHtml = tutorialData.map((section, index) => `
        <button onclick="goToSection(${index})" 
            class="group relative overflow-hidden bg-[#111] border border-white/10 rounded-2xl p-8 text-left transition-all duration-300 hover:border-amber-500/50 hover:-translate-y-1 hover:shadow-[0_10px_40px_-10px_rgba(245,184,0,0.15)]">
            <!-- Aura Bg -->
            <div class="absolute inset-0 bg-gradient-to-br from-amber-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            
            <div class="relative z-10 flex items-start gap-6">
                <div class="w-14 h-14 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-500 group-hover:bg-amber-500 group-hover:text-black transition-all duration-300">
                    <iconify-icon icon="${section.icon}" width="32"></iconify-icon>
                </div>
                <div class="flex-1">
                    <h3 class="text-xl font-bold text-white mb-2 group-hover:text-amber-500 transition-colors">${section.title}</h3>
                    <p class="text-neutral-500 text-sm leading-relaxed mb-4 min-h-[40px]">${section.description}</p>
                    <div class="flex items-center gap-2 text-xs font-mono text-neutral-400 uppercase tracking-widest group-hover:text-white transition-colors">
                        <span>${section.steps.length} Steps</span>
                        <iconify-icon icon="ph:arrow-right-bold" class="group-hover:translate-x-1 transition-transform"></iconify-icon>
                    </div>
                </div>
            </div>
        </button>
    `).join('');

    appRoot.innerHTML = `
        <div class="max-w-[1200px] mx-auto px-6 py-12 animate-fade-in">
            <!-- Hero -->
            <div class="text-center mb-16">
                 <div class="inline-flex items-center gap-2 px-3 py-1 mb-6 border border-amber-500/20 rounded-full bg-amber-500/5">
                    <div class="w-1.5 h-1.5 bg-amber-500 rounded-full animate-pulse"></div>
                    <span class="text-[10px] font-mono text-amber-500 uppercase tracking-widest">Tutorial Center</span>
                </div>
                <h1 class="text-4xl md:text-5xl font-bold text-white mb-6">
                    Master the <span class="text-amber-500">Genesis</span> Platform
                </h1>
                <p class="text-neutral-400 max-w-lg mx-auto">Select a module below to start your step-by-step learning journey.</p>
            </div>

            <!-- Grid -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                ${gridHtml}
            </div>
        </div>
    `;
}

function renderSectionView(sectionIndex) {
    const section = tutorialData[sectionIndex];
    if (!section) return;

    state.view = 'section';
    state.currentSectionIndex = sectionIndex;

    // Render Container
    appRoot.innerHTML = `
        <div class="max-w-[1400px] mx-auto px-6 py-8 animate-fade-in flex flex-col min-h-[80vh]">
            <!-- Top Bar -->
            <div class="flex items-center justify-between mb-8 pb-6 border-b border-white/5">
                <button onclick="renderHome()" class="group relative inline-flex gap-3 uppercase transition-all cursor-pointer text-sm font-medium text-white tracking-wider opacity-100 border-transparent border-2 rounded-xl items-center justify-center" style="padding: 12px 20px; background: linear-gradient(0deg, #000, #272727); border-radius: 10px; border: none; color: white; position: relative; cursor: pointer; font-weight: 900; transition-duration: .2s;">
                    <div class="absolute left-0 top-0 w-full h-full rounded-xl pointer-events-none" style="left: -2px; top: -2px; border-radius: 10px; background: linear-gradient(45deg, #fb0094, #0000ff, #00ff00, #ffff00, #ff0000, #fb0094, #0000ff, #00ff00, #ffff00, #ff0000); background-size: 400%; width: calc(100% + 4px); height: calc(100% + 4px); z-index: -1; animation: steam 20s linear infinite;"></div>
                    <div class="absolute left-0 top-0 w-full h-full rounded-xl pointer-events-none" style="left: -2px; top: -2px; border-radius: 10px; background: linear-gradient(45deg, #fb0094, #0000ff, #00ff00, #ffff00, #ff0000, #fb0094, #0000ff, #00ff00, #ffff00, #ff0000); background-size: 400%; width: calc(100% + 4px); height: calc(100% + 4px); z-index: -1; animation: steam 20s linear infinite; filter: blur(50px);"></div>
                    <span class="relative z-30 font-medium">Back to Home</span>
                    <span class="relative flex h-5 w-5 items-center justify-center z-30 group-hover:text-amber-500 transition-colors">
                        <iconify-icon icon="ph:house-bold"></iconify-icon>
                    </span>
                </button>

                <div class="flex items-center gap-3">
                    <iconify-icon icon="${section.icon}" class="text-amber-500 text-xl"></iconify-icon>
                    <span class="font-bold text-white text-lg hidden md:block">${section.title}</span>
                </div>

                <div class="flex items-center gap-1.5" id="progress-dots">
                    <!-- Dots injected via JS -->
                </div>
            </div>

            <!-- Content Area -->
            <div class="flex-1 flex items-center justify-center relative">
                <div id="step-container" class="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
                    <!-- Content injected via updateStep() -->
                </div>
            </div>

            <!-- Bottom Nav -->
            <div class="mt-12 flex items-center justify-between">
                <button id="btn-prev" onclick="navigate('prev')" class="px-6 py-3 rounded-xl border border-white/10 text-neutral-400 hover:text-white hover:bg-white/5 transition-all flex items-center gap-2 disabled:opacity-30 disabled:cursor-not-allowed">
                    <iconify-icon icon="ph:arrow-left-bold"></iconify-icon>
                    <span>Previous</span>
                </button>

                <div class="text-sm font-mono text-neutral-500" id="step-counter">
                    Step 1 / ${section.steps.length}
                </div>

                <button id="btn-next" onclick="navigate('next')" class="px-6 py-3 rounded-xl bg-amber-500 text-black font-bold hover:bg-amber-400 transition-all flex items-center gap-2 shadow-[0_0_20px_rgba(245,184,0,0.3)] hover:shadow-[0_0_30px_rgba(245,184,0,0.5)]">
                    <span>Next Step</span>
                    <iconify-icon icon="ph:arrow-right-bold"></iconify-icon>
                </button>
            </div>
        </div>
    `;

    updateStep(0, false);
}

function updateStep(stepIndex, animate = true) {
    const section = tutorialData[state.currentSectionIndex];
    const step = section.steps[stepIndex];
    const container = document.getElementById('step-container');
    const direction = stepIndex > state.currentStepIndex ? 'next' : 'prev';

    state.currentStepIndex = stepIndex;

    // Update Dots
    const dotsContainer = document.getElementById('progress-dots');
    dotsContainer.innerHTML = section.steps.map((_, idx) => `
        <div class="h-1.5 rounded-full transition-all duration-300 ${idx === stepIndex ? 'w-8 bg-amber-500' : (idx < stepIndex ? 'w-1.5 bg-amber-500/50' : 'w-1.5 bg-white/10')}"></div>
    `).join('');

    // Update Counter
    document.getElementById('step-counter').textContent = `Step ${stepIndex + 1} / ${section.steps.length}`;

    // Update Buttons
    const btnPrev = document.getElementById('btn-prev');
    const btnNext = document.getElementById('btn-next');

    btnPrev.disabled = stepIndex === 0;

    if (stepIndex === section.steps.length - 1) {
        btnNext.innerHTML = `<span>Complete</span><iconify-icon icon="ph:check-bold"></iconify-icon>`;
        btnNext.classList.replace('bg-amber-500', 'bg-green-500');
        btnNext.onclick = () => renderHome();
    } else {
        btnNext.innerHTML = `<span>Next Step</span><iconify-icon icon="ph:arrow-right-bold"></iconify-icon>`;
        btnNext.classList.replace('bg-green-500', 'bg-amber-500');
        btnNext.onclick = () => navigate('next');
    }

    // Content HTML
    const contentHtml = `
        <!-- Image Side -->
        <div class="order-2 lg:order-1 relative group perspective-container flex justify-center">
           <div class="iphone-frame-wrapper transform transition-all duration-500 hover:scale-105">
                <div class="relative bg-black rounded-[2.5rem] p-3 shadow-2xl border border-white/10 ring-1 ring-black">
                     <!-- Screen -->
                     <div class="relative rounded-[2rem] overflow-hidden aspect-[9/19.5] bg-[#050505]">
                         <img src="${step.image}" class="w-full h-full object-cover" alt="${step.title}">
                         <!-- Home Indicator -->
                         <div class="absolute bottom-2 left-1/2 -translate-x-1/2 w-1/3 h-1 bg-white/20 rounded-full backdrop-blur-md"></div>
                     </div>
                     <!-- Reflection Glare -->
                     <div class="absolute inset-0 rounded-[2.5rem] bg-gradient-to-tr from-white/5 to-transparent pointer-events-none"></div>
                </div>
           </div>
        </div>

        <!-- Text Side -->
        <div class="order-1 lg:order-2 space-y-6">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-lg bg-amber-500/10 text-amber-500 text-xs font-bold uppercase tracking-wider">
                Step ${stepIndex + 1}
            </div>
            
            <h2 class="text-4xl md:text-5xl font-bold text-white leading-tight">
                ${step.title}
            </h2>
            
            <p class="text-lg text-neutral-400 leading-relaxed border-l-2 border-white/10 pl-6">
                ${step.description}
            </p>
        </div>
    `;

    // Animate Transition
    if (animate) {
        gsap.to(container, {
            opacity: 0,
            x: direction === 'next' ? -20 : 20,
            duration: 0.2,
            onComplete: () => {
                container.innerHTML = contentHtml;
                init3DTilt(); // Re-init tilt on new element
                gsap.fromTo(container,
                    { opacity: 0, x: direction === 'next' ? 20 : -20 },
                    { opacity: 1, x: 0, duration: 0.3, ease: 'power2.out' }
                );
            }
        });
    } else {
        container.innerHTML = contentHtml;
        init3DTilt();
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ACTIONS & UTILS
// ─────────────────────────────────────────────────────────────────────────────

window.goToSection = (index) => {
    renderSectionView(index);
}

window.renderHome = renderHome;

window.navigate = (direction) => {
    const { currentSectionIndex, currentStepIndex } = state;
    const section = tutorialData[currentSectionIndex];

    if (direction === 'next' && currentStepIndex < section.steps.length - 1) {
        updateStep(currentStepIndex + 1);
    } else if (direction === 'prev' && currentStepIndex > 0) {
        updateStep(currentStepIndex - 1);
    }
}

// 3D Tilt Effect adapted for single item
function init3DTilt() {
    const wrapper = document.querySelector('.iphone-frame-wrapper');
    if (!wrapper || window.innerWidth < 1024) return; // Disable on mobile

    wrapper.addEventListener('mousemove', (e) => {
        const rect = wrapper.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;

        // Calculate percentages (-1 to 1)
        const xPct = (x / rect.width - 0.5) * 2;
        const yPct = (y / rect.height - 0.5) * 2;

        gsap.to(wrapper, {
            rotationY: xPct * 15,
            rotationX: -yPct * 15,
            duration: 0.5,
            ease: 'power2.out',
            transformPerspective: 1000
        });
    });

    wrapper.addEventListener('mouseleave', () => {
        gsap.to(wrapper, {
            rotationY: 0,
            rotationX: 0,
            duration: 0.6,
            ease: 'elastic.out(1, 0.8)'
        });
    });
}

// Init
document.addEventListener('DOMContentLoaded', initApp);
